# fly.toml app configuration file generated for links-techops-white-mountain-4284 on 2023-12-28T17:07:26-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "links-techops-white-mountain-4284"
primary_region = "dfw"

[build]

[http_service]
  internal_port = 3333
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
